/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef HELLOWORLD_ARGS_H
#define HELLOWORLD_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */ 

#include <openenclave/bits/result.h>

typedef struct _enclave_helloworld_args_t {
    oe_result_t _result;
 } enclave_helloworld_args_t;

typedef struct _host_helloworld_args_t {
    oe_result_t _result;
 } host_helloworld_args_t;

/* trusted function ids */
enum {
    fcn_id_enclave_helloworld = 0,
    fcn_id_trusted_call_id_max = OE_ENUM_MAX
};


/* untrusted function ids */
enum {
    fcn_id_host_helloworld = 0,
    fcn_id_untrusted_call_max = OE_ENUM_MAX
};


#endif // HELLOWORLD_ARGS_H
